<?php
////////////////////////////////////////////////////////////////////////////////
//
//  Copyright © 2010 World Wide Web Consortium, 
//  (Massachusetts Institute of Technology, European Research 
//  Consortium for Informatics and Mathematics, Keio 
//  University). All Rights Reserved. 
//  Copyright © 2010 Hewlett-Packard Development Company, L.P. 
// 
//  This work is distributed under the W3C¬ Software License 
//  [1] in the hope that it will be useful, but WITHOUT ANY 
//  WARRANTY; without even the implied warranty of 
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
// 
//  [1] http://www.w3.org/Consortium/Legal/2002/copyright-software-20021231 
//
//////////////////////////////////////////////////////////////////////////////// 

//////////////////////////////////////////////////////////////////////////////// 
//
//  grandfather.php
//
//  Adapted from Mobile Test Harness [1]
//
//    File: grandfather.php
//      Lines: 103-142
//
//  where herein specific contents provided by the original harness have
//  been adapted for CSS2.1 conformance testing. Separately, controls have
//  been added to allow entering data for user agents other than the one
//  accessing the harness, and the means by which test presentation order
//  is provided have been altered. Separately, the ability to request
//  only those tests in a particular named group has been added.
//
// [1] http://dev.w3.org/cvsweb/2007/mobile-test-harness/
//
//////////////////////////////////////////////////////////////////////////////// 

require_once("./lib_css2.1_harness/class.css_page.phi");
require_once("./lib_test_harness/class.db_connection.phi");
//require_once("./lib_css2.1_harness/class.test_suite.phi");
//require_once("./lib_css2.1_harness/class.user_agent.phi");
//require_once("./lib_css2.1_harness/class.test_groups.phi");
//require_once("./lib_css2.1_harness/class.test_cases.phi");

////////////////////////////////////////////////////////////////////////////////
//
//  class testsuite_page
//
//  A class for generating a page for selecting how tests in a particular 
//  test suite will be presented for inspection. The page includes allowing
//  results to be entered for the user agent accessing the harness or for
//  a user provided user agent. The page further includes requesting
//  to see all of the test cases in the suite, only those test cases in a
//  particular named group, or individual cases. Requests can also be made
//  that successive test cases be presented in the order that they are listed
//  or sorted according to how many response have been entered for the user 
//  agent in question.
//
////////////////////////////////////////////////////////////////////////////////
class grandfather extends css_page
{  
  ////////////////////////////////////////////////////////////////////////////
  //
  //  Instance variables.
  //
  ////////////////////////////////////////////////////////////////////////////


  ////////////////////////////////////////////////////////////////////////////
  //
  //  Constructor.
  //
  //  The URL accessing the page generated by an object of this class must
  //  identify a valid testsuite:
  //
  //    testsuite.php?s=[testsuite]
  //
  //  If no test suite is identified or if the identified test suite is
  //  not valid, then an error is generated.
  //
  //  The URL accessing the page generated by an object of this class may
  //  also identify an alternate user agent for which data is to be entered:
  //
  //     testsuite.php?s=[testsuite]&u=[id]
  //     testsuite.php?s=[testsuite]&u=[user-agent string]
  //
  //  If no alternate user agent is identified or if the identified user
  //  agent is not valid, then the user agent string of the browser accessing
  //  the harness is used.
  //
  //  All other URL parameters are ignored.
  //
  ////////////////////////////////////////////////////////////////////////////
  function grandfather() 
  {
    parent::css_page();

  }  
  
  ////////////////////////////////////////////////////////////////////////////
  //
  // write_body_content()
  //
  ////////////////////////////////////////////////////////////////////////////
  function write_body_content($indent = '') {

    $db = new db_connection();

    // update results 
    echo "<table>";
    $sql = "SELECT id, testcase FROM testcases WHERE testsuite='CSS21_HTML_RC2' AND grandfather='1'";
    $r = $db->query($sql);
    $db_list = $r->fetch_table(); 
    foreach ($db_list as $db_data) {
      $new_testcase_id = $db_data['id'];
      $testcase = $db_data['testcase'];
      
      echo "<tr><td>" . $new_testcase_id . "<td colspan='999'>" . $testcase;
      
      $sql  = "SELECT id FROM testcases ";
      $sql .= "WHERE testcases.testcase='{$testcase}' AND testcases.testsuite='CSS21_HTML_RC1' ";
      $sql .= "LIMIT 1";
      $r = $db->query($sql);
      if (! $r->is_false()) {
        $testcase_list = $r->fetch_table();
        $old_testcase_id = $testcase_list[0]['id'];
        
        $sql  = "SELECT useragent_id, source, result, results.modified FROM results ";
        $sql .= "WHERE testcase_id='{$old_testcase_id}'";
        //print "<td>" . $sql;      
        $r = $db->query($sql);
        if (! $r->is_false()) {
          $result_list = $r->fetch_table();
          foreach ($result_list as $result_data) {
            $useragent_id = $result_data['useragent_id'];
            $source = $result_data['source'];
            $result = $result_data['result'];
            $modified = $result_data['modified'];
            
            echo "<tr><td>&nbsp;<td>" . $useragent_id . "<td>" . $source . "<td>" . $result . "<td>" . $modified;
            
            $sql  = "INSERT INTO results (testcase_id, useragent_id, source, result, modified) VALUES ";
            $sql .= "('{$new_testcase_id}', '{$useragent_id}', '{$source}+', '{$result}', '{$modified}')";
            //print "<td>" . $sql;        
            $db->query($sql);
          }
        }
      }
      
      $sql  = "UPDATE testcases SET grandfather='2' WHERE id='{$new_testcase_id}'";
      //print "<td>". $sql;      
      $db->query($sql);      
    }
    echo "</table>";
    
    // update results 
    echo "<table>";
    $sql = "SELECT id, testcase FROM testcases WHERE testsuite='CSS21_XHTML_RC2' AND grandfather='1'";
    $r = $db->query($sql);
    $db_list = $r->fetch_table(); 
    foreach ($db_list as $db_data) {
      $new_testcase_id = $db_data['id'];
      $testcase = $db_data['testcase'];
      
      echo "<tr><td>" . $new_testcase_id . "<td colspan='999'>" . $testcase;
      
      $sql  = "SELECT id FROM testcases ";
      $sql .= "WHERE testcases.testcase='{$testcase}' AND testcases.testsuite='CSS21_XHTML_RC1' ";
      $sql .= "LIMIT 1";
      $r = $db->query($sql);
      if (! $r->is_false()) {
        $testcase_list = $r->fetch_table();
        $old_testcase_id = $testcase_list[0]['id'];
        
        $sql  = "SELECT useragent_id, source, result, results.modified FROM results ";
        $sql .= "WHERE testcase_id='{$old_testcase_id}'";
        //print "<td>" . $sql;      
        $r = $db->query($sql);
        if (! $r->is_false()) {
          $result_list = $r->fetch_table();
          foreach ($result_list as $result_data) {
            $useragent_id = $result_data['useragent_id'];
            $source = $result_data['source'];
            $result = $result_data['result'];
            $modified = $result_data['modified'];
            
            echo "<tr><td>&nbsp;<td>" . $useragent_id . "<td>" . $source . "<td>" . $result . "<td>" . $modified;
            
            $sql  = "INSERT INTO results (testcase_id, useragent_id, source, result, modified) VALUES ";
            $sql .= "('{$new_testcase_id}', '{$useragent_id}', '{$source}+', '{$result}', '{$modified}')";
            //print "<td>" . $sql;        
            $db->query($sql);
          }
        }
      }

      $sql  = "UPDATE testcases SET grandfather='2' WHERE id='{$new_testcase_id}'";
      //print "<td>". $sql;      
      $db->query($sql);      
    }
    echo "</table>";
    
  }
}

$page = new grandfather();
$page -> write();

?>
